// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: books.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	//Create Book
	CreateBook(ctx context.Context, in *CreateNewBookReq, opts ...grpc.CallOption) (*CreateBookRes, error)
	//List All Books
	ListAllBooks(ctx context.Context, in *CreateNewBookReq, opts ...grpc.CallOption) (BookService_ListAllBooksClient, error)
	//Search Books
	SearchBooks(ctx context.Context, in *SearchBooksReq, opts ...grpc.CallOption) (BookService_SearchBooksClient, error)
	//Update Book
	UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*UpdateBookRes, error)
	//Delete Book
	DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*DeleteBookRes, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateNewBookReq, opts ...grpc.CallOption) (*CreateBookRes, error) {
	out := new(CreateBookRes)
	err := c.cc.Invoke(ctx, "/booksproto.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) ListAllBooks(ctx context.Context, in *CreateNewBookReq, opts ...grpc.CallOption) (BookService_ListAllBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/booksproto.BookService/ListAllBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceListAllBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookService_ListAllBooksClient interface {
	Recv() (*ListAllBooksRes, error)
	grpc.ClientStream
}

type bookServiceListAllBooksClient struct {
	grpc.ClientStream
}

func (x *bookServiceListAllBooksClient) Recv() (*ListAllBooksRes, error) {
	m := new(ListAllBooksRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) SearchBooks(ctx context.Context, in *SearchBooksReq, opts ...grpc.CallOption) (BookService_SearchBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[1], "/booksproto.BookService/SearchBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceSearchBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookService_SearchBooksClient interface {
	Recv() (*SearchBooksRes, error)
	grpc.ClientStream
}

type bookServiceSearchBooksClient struct {
	grpc.ClientStream
}

func (x *bookServiceSearchBooksClient) Recv() (*SearchBooksRes, error) {
	m := new(SearchBooksRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*UpdateBookRes, error) {
	out := new(UpdateBookRes)
	err := c.cc.Invoke(ctx, "/booksproto.BookService/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*DeleteBookRes, error) {
	out := new(DeleteBookRes)
	err := c.cc.Invoke(ctx, "/booksproto.BookService/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	//Create Book
	CreateBook(context.Context, *CreateNewBookReq) (*CreateBookRes, error)
	//List All Books
	ListAllBooks(*CreateNewBookReq, BookService_ListAllBooksServer) error
	//Search Books
	SearchBooks(*SearchBooksReq, BookService_SearchBooksServer) error
	//Update Book
	UpdateBook(context.Context, *UpdateBookReq) (*UpdateBookRes, error)
	//Delete Book
	DeleteBook(context.Context, *DeleteBookReq) (*DeleteBookRes, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *CreateNewBookReq) (*CreateBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) ListAllBooks(*CreateNewBookReq, BookService_ListAllBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAllBooks not implemented")
}
func (UnimplementedBookServiceServer) SearchBooks(*SearchBooksReq, BookService_SearchBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchBooks not implemented")
}
func (UnimplementedBookServiceServer) UpdateBook(context.Context, *UpdateBookReq) (*UpdateBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookServiceServer) DeleteBook(context.Context, *DeleteBookReq) (*DeleteBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booksproto.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateNewBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_ListAllBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateNewBookReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).ListAllBooks(m, &bookServiceListAllBooksServer{stream})
}

type BookService_ListAllBooksServer interface {
	Send(*ListAllBooksRes) error
	grpc.ServerStream
}

type bookServiceListAllBooksServer struct {
	grpc.ServerStream
}

func (x *bookServiceListAllBooksServer) Send(m *ListAllBooksRes) error {
	return x.ServerStream.SendMsg(m)
}

func _BookService_SearchBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchBooksReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).SearchBooks(m, &bookServiceSearchBooksServer{stream})
}

type BookService_SearchBooksServer interface {
	Send(*SearchBooksRes) error
	grpc.ServerStream
}

type bookServiceSearchBooksServer struct {
	grpc.ServerStream
}

func (x *bookServiceSearchBooksServer) Send(m *SearchBooksRes) error {
	return x.ServerStream.SendMsg(m)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booksproto.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*UpdateBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booksproto.BookService/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBook(ctx, req.(*DeleteBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booksproto.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookService_DeleteBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAllBooks",
			Handler:       _BookService_ListAllBooks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchBooks",
			Handler:       _BookService_SearchBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "books.proto",
}
